# Generated by Django 6.0.5 on 2026-05-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbk_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='user',
        ),
    ]
